# Site settings
title: Internet Governance Experts
description: >
  Development containers documentation and specification page.

# baseurl: / # the subpath of your site, e.g. /blog/
url: https://igecloud.dev/devcontainers
git_address: https://github.com/igeclouds/devcontainers.github.io
git_edit_address: https://github.com/igeclouds/devcontainers.github.io/settings/pages/blob/gh-pages

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - github-pages
  - jemoji


exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
  - resources

timezone: Europe/London

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: kubernetes

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _implementors
    type: implementors
  values:
    layout: implementors
    sectionid: implementors

kubernetes:
  docs:
    permalink: /:kubernetes/:path/
    output: true
  posts:
    permalink: /kubernetes/:title
    output: true
  implementors:
    permalink: /:kubernetes/:path/
    output: true
